<?xml version="1.0" encoding="utf-8"?>
<definitions xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://control.cte.gob/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="VehiculosComunicacionControlService" targetNamespace="http://control.cte.gob/" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <types>
    <xsd:schema>
      <xsd:import schemaLocation="http://10.10.200.115:8081/ComunicacionWEB/VehiculosComunicacionControlPort?xsd=1" namespace="http://control.cte.gob/" />
    </xsd:schema>
  </types>
  <message name="obtenerVehiculoPlacaChasis">
    <part name="parameters" element="tns:obtenerVehiculoPlacaChasis" />
  </message>
  <message name="obtenerVehiculoPlacaChasisResponse">
    <part name="parameters" element="tns:obtenerVehiculoPlacaChasisResponse" />
  </message>
  <message name="obtenerVehiculoIdentificacion">
    <part name="parameters" element="tns:obtenerVehiculoIdentificacion" />
  </message>
  <message name="obtenerVehiculoIdentificacionResponse">
    <part name="parameters" element="tns:obtenerVehiculoIdentificacionResponse" />
  </message>
  <portType name="VehiculosComunicacionControlDelegate">
    <operation name="obtenerVehiculoPlacaChasis">
      <input message="tns:obtenerVehiculoPlacaChasis" />
      <output message="tns:obtenerVehiculoPlacaChasisResponse" />
    </operation>
    <operation name="obtenerVehiculoIdentificacion">
      <input message="tns:obtenerVehiculoIdentificacion" />
      <output message="tns:obtenerVehiculoIdentificacionResponse" />
    </operation>
  </portType>
  <binding name="VehiculosComunicacionControlPortBinding" type="tns:VehiculosComunicacionControlDelegate">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <operation name="obtenerVehiculoPlacaChasis">
      <soap:operation soapAction="" />
      <input>
        <soap:body use="literal" />
      </input>
      <output>
        <soap:body use="literal" />
      </output>
    </operation>
    <operation name="obtenerVehiculoIdentificacion">
      <soap:operation soapAction="" />
      <input>
        <soap:body use="literal" />
      </input>
      <output>
        <soap:body use="literal" />
      </output>
    </operation>
  </binding>
  <service name="VehiculosComunicacionControlService">
    <port name="VehiculosComunicacionControlPort" binding="tns:VehiculosComunicacionControlPortBinding">
      <soap:address location="http://10.10.200.115:8081/ComunicacionWEB/VehiculosComunicacionControlPort" />
    </port>
  </service>
</definitions>